<a href="https://colab.research.google.com/github/Xu-Ruixin/Multilingual-Phoneme-Recognition/blob/main/CS2CS_Phoneme_Recognition_(Piloting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Sun Dec  3 17:17:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
%%capture
!pip install -U datasets
!pip install -U transformers[torch]
!pip install torchaudio
!pip install librosa
!pip install -U huggingface_hub
!pip install jiwer
!pip install accelerate -U
!pip install phonemizer
!apt install git-lfs
!sudo apt-get install festival espeak-ng mbrola
!apt search mbrola
!apt install git-lfs

In [ ]:
from huggingface_hub import notebook_login

notebook_login()

In [ ]:
from datasets import load_dataset, load_metric, Audio

# common_voice_train = load_dataset("facebook/voxpopuli", "fi", split="train+validation")
common_voice_train = load_dataset("facebook/voxpopuli", "cs", split="validation")
common_voice_test = load_dataset("facebook/voxpopuli", "cs", split="test")
common_voice_test_2 = common_voice_test

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/3 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [ ]:
common_voice_train

Dataset({
    features: ['audio_id', 'language', 'audio', 'raw_text', 'normalized_text', 'gender', 'speaker_id', 'is_gold_transcript', 'accent'],
    num_rows: 1103
})

In [ ]:
sentence = "normalized_text"
col_names = list(common_voice_train.features.keys())
col_names.remove(sentence)
col_names.remove("audio")
common_voice_train = common_voice_train.remove_columns(col_names)
common_voice_test = common_voice_test.remove_columns(col_names)

In [ ]:
common_voice_train

Dataset({
    features: ['audio', 'normalized_text'],
    num_rows: 1103
})

In [ ]:
common_voice_test

Dataset({
    features: ['audio', 'normalized_text'],
    num_rows: 1123
})

In [ ]:
from datasets import ClassLabel
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=10):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    display(HTML(df.to_html()))

In [ ]:
show_random_elements(common_voice_train, num_examples=1)

In [ ]:
import re
chars_to_remove_regex = '[\,\?\.\!\-\;\:\"\“\%\‘\”\�\']'

def remove_special_characters(batch):
    batch[sentence] = re.sub(chars_to_remove_regex, '', batch[sentence]).lower()
    return batch

In [ ]:
common_voice_train = common_voice_train.map(remove_special_characters)
common_voice_test = common_voice_test.map(remove_special_characters)

Map:   0%|          | 0/1103 [00:00<?, ? examples/s]

Map:   0%|          | 0/1123 [00:00<?, ? examples/s]

In [ ]:
show_random_elements(common_voice_train, 1)

In [ ]:
from transformers import Wav2Vec2Processor

# processor = Wav2Vec2Processor(feature_extractor=feature_extractor, tokenizer=tokenizer)
processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-lv-60-espeak-cv-ft")

preprocessor_config.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/321 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/4.64k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

In [ ]:
common_voice_train = common_voice_train.cast_column("audio", Audio(sampling_rate=16_000))
common_voice_test = common_voice_test.cast_column("audio", Audio(sampling_rate=16_000))

In [ ]:
common_voice_train[0]["audio"]

{'path': '/root/.cache/huggingface/datasets/downloads/extracted/878bb93f50316d028ef5fbc7cc348b2f97af8adc6c081131daea7c82daa38113/dev_part_0/20171115-0900-PLENARY-12-cs_20171115-13:38:25_3.wav',
 'array': array([-0.0010376 , -0.00476074, -0.00054932, ..., -0.00021362,
        -0.00018311, -0.0010376 ]),
 'sampling_rate': 16000}

In [ ]:
import IPython.display as ipd
import numpy as np
import random

rand_int = random.randint(0, len(common_voice_train)-1)

print(common_voice_train[rand_int]["normalized_text"])
ipd.Audio(data=common_voice_train[rand_int]["audio"]["array"], autoplay=True, rate=16000)

stejný by měl být i náš pohled zaměřený na výsledek a výkonnost a děkuji že jste to také zmínil pane komisaři


In [ ]:
rand_int = random.randint(0, len(common_voice_train)-1)

print("Target text:", common_voice_train[rand_int]["normalized_text"])
print("Input array shape:", common_voice_train[rand_int]["audio"]["array"].shape)
print("Sampling rate:", common_voice_train[rand_int]["audio"]["sampling_rate"])

Target text: přesto se nakonec ze všech možných modelů rozhodla pro jeden z nejméně ambiciózních cílů pro období do roku
Input array shape: (105599,)
Sampling rate: 16000


In [ ]:
def prepare_dataset(batch):
    audio = batch["audio"]

    # batched output is "un-batched"
    batch["input_values"] = processor(audio["array"], sampling_rate=audio["sampling_rate"]).input_values[0]
    batch["input_length"] = len(batch["input_values"])

    with processor.as_target_processor():
        batch["labels"] = processor(batch["normalized_text"]).input_ids
    return batch

In [ ]:
common_voice_train = common_voice_train.map(prepare_dataset, remove_columns=common_voice_train.column_names)
common_voice_test = common_voice_test.map(prepare_dataset, remove_columns=common_voice_test.column_names)

Map:   0%|          | 0/1103 [00:00<?, ? examples/s]

/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:155: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(


Map:   0%|          | 0/1123 [00:00<?, ? examples/s]

In [ ]:
max_input_length_in_sec = 5.0
common_voice_train = common_voice_train.filter(lambda x: x < max_input_length_in_sec * processor.feature_extractor.sampling_rate, input_columns=["input_length"])

common_voice_test = common_voice_test.filter(lambda x: x < max_input_length_in_sec * processor.feature_extractor.sampling_rate, input_columns=["input_length"])

Filter:   0%|          | 0/1103 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1123 [00:00<?, ? examples/s]

In [ ]:
common_voice_train

Dataset({
    features: ['input_values', 'input_length', 'labels'],
    num_rows: 185
})

In [ ]:
common_voice_test

Dataset({
    features: ['input_values', 'input_length', 'labels'],
    num_rows: 191
})

In [ ]:
import torch

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union

@dataclass
class DataCollatorCTCWithPadding:
    """
    Data collator that will dynamically pad the inputs received.
    Args:
        processor (:class:`~transformers.Wav2Vec2Processor`)
            The processor used for proccessing the data.
        padding (:obj:`bool`, :obj:`str` or :class:`~transformers.tokenization_utils_base.PaddingStrategy`, `optional`, defaults to :obj:`True`):
            Select a strategy to pad the returned sequences (according to the model's padding side and padding index)
            among:
            * :obj:`True` or :obj:`'longest'`: Pad to the longest sequence in the batch (or no padding if only a single
              sequence if provided).
            * :obj:`'max_length'`: Pad to a maximum length specified with the argument :obj:`max_length` or to the
              maximum acceptable input length for the model if that argument is not provided.
            * :obj:`False` or :obj:`'do_not_pad'` (default): No padding (i.e., can output a batch with sequences of
              different lengths).
    """

    processor: Wav2Vec2Processor
    padding: Union[bool, str] = True

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        # split inputs and labels since they have to be of different lenghts and need
        # different padding methods
        input_features = [{"input_values": feature["input_values"]} for feature in features]
        label_features = [{"input_ids": feature["labels"]} for feature in features]

        batch = self.processor.pad(
            input_features,
            padding=self.padding,
            return_tensors="pt",
        )
        with self.processor.as_target_processor():
            labels_batch = self.processor.pad(
                label_features,
                padding=self.padding,
                return_tensors="pt",
            )

        # replace padding with -100 to ignore loss correctly
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        batch["labels"] = labels

        return batch

In [ ]:
data_collator = DataCollatorCTCWithPadding(processor=processor, padding=True)

In [ ]:
wer_metric = load_metric("wer")

<ipython-input-26-605de035dfd7>:1: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  wer_metric = load_metric("wer")


In [ ]:
def compute_metrics(pred):
    pred_logits = pred.predictions
    pred_ids = np.argmax(pred_logits, axis=-1)

    pred.label_ids[pred.label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.batch_decode(pred_ids)
    # we do not want to group tokens when computing the metrics
    label_str = processor.batch_decode(pred.label_ids, group_tokens=False)

    wer = wer_metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer}

In [ ]:
from transformers import Wav2Vec2ForCTC

dropout_ratio = 0.2

model = Wav2Vec2ForCTC.from_pretrained(
    "facebook/wav2vec2-lv-60-espeak-cv-ft",
    attention_dropout=dropout_ratio,
    hidden_dropout=dropout_ratio,
    feat_proj_dropout=dropout_ratio,
    mask_time_prob=0.05,
    layerdrop=0.0,
    ctc_loss_reduction="mean",
    pad_token_id=processor.tokenizer.pad_token_id,
    vocab_size=len(processor.tokenizer),
)

config.json:   0%|          | 0.00/1.86k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

Some weights of the model checkpoint at facebook/wav2vec2-lv-60-espeak-cv-ft were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_v', 'wav2vec2.encoder.pos_conv_embed.conv.weight_g']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-lv-60-espeak-cv-ft and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably

In [ ]:
model.freeze_feature_extractor()

/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/modeling_wav2vec2.py:1913: FutureWarning: The method `freeze_feature_extractor` is deprecated and will be removed in Transformers v5. Please use the equivalent `freeze_feature_encoder` method instead.
  warnings.warn(


In [ ]:
from transformers import TrainingArguments

repo_name = "wav2vec2-large-xls-r-300m-cs-colab-phoneme"

training_args = TrainingArguments(
  output_dir=repo_name,
  group_by_length=True,
  per_device_train_batch_size=16,
  gradient_accumulation_steps=2,
  evaluation_strategy="steps",
  num_train_epochs=50,
  gradient_checkpointing=True,
  fp16=True,
  save_steps=100,
  eval_steps=100,
  logging_steps=100,
  learning_rate=1e-5,
  warmup_steps=500,
  save_total_limit=2,
  push_to_hub=True,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    data_collator=data_collator,
    args=training_args,
    compute_metrics=compute_metrics,
    train_dataset=common_voice_train,
    eval_dataset=common_voice_test,
    tokenizer=processor.feature_extractor,
)

To avoid inactivity: inspect -> console -> copy-paste

```javascript
function ConnectButton(){
    console.log("Connect pushed");
    document.querySelector("#top-toolbar > colab-connect-button").shadowRoot.querySelector("#connect").click()
}
setInterval(ConnectButton,60000);
```

In [ ]:
trainer.evaluate()

/usr/local/lib/python3.10/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:155: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(


{'eval_loss': 4.351444721221924,
 'eval_wer': 0.6578978693012737,
 'eval_runtime': 17.5397,
 'eval_samples_per_second': 10.89,
 'eval_steps_per_second': 1.368}

In [ ]:
trainer.train()

/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


TrainOutput(global_step=300, training_loss=3.074987386067708, metrics={'train_runtime': 907.4959, 'train_samples_per_second': 10.193, 'train_steps_per_second': 0.331, 'total_flos': 1.2139978977341445e+18, 'train_loss': 3.074987386067708, 'epoch': 50.0})

In [ ]:
trainer.evaluate()

{'eval_loss': 1.938826322555542,
 'eval_wer': 0.44625639804785144,
 'eval_runtime': 10.2734,
 'eval_samples_per_second': 18.592,
 'eval_steps_per_second': 2.336,
 'epoch': 50.0}

In [ ]:
input_dict = processor(common_voice_test[0]["input_values"], return_tensors="pt", padding=True)
print(input_dict)

logits = model(input_dict.input_values.to("cuda")).logits
print(logits)

pred_ids = torch.argmax(logits, dim=-1)[0]
print(pred_ids)

print("Prediction:")
print(processor.decode(pred_ids))

print("\nReference:")
print(common_voice_test_2[0][sentence].lower())

It is strongly recommended to pass the ``sampling_rate`` argument to this function. Failing to do so can result in silent errors that might be hard to debug.


{'input_values': tensor([[-0.0042,  0.0136, -0.0304,  ...,  0.0295,  0.0304,  0.0276]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1]], dtype=torch.int32)}
tensor([[[ 13.3438, -18.9688, -18.5000,  ..., -17.5781, -19.0781, -18.3125],
         [ 13.5859, -19.3750, -18.8750,  ..., -17.9062, -19.4844, -18.6406],
         [ 13.3594, -18.9531, -18.4531,  ..., -17.5000, -19.0938, -18.2969],
         ...,
         [  8.7578, -13.3750, -13.0938,  ..., -12.4844, -13.6562, -12.9141],
         [  7.9062, -12.7031, -12.4375,  ..., -11.8516, -12.9844, -12.2891],
         [  8.5000, -13.4844, -13.1094,  ..., -12.5547, -13.7734, -13.1016]]],
       device='cuda:0', grad_fn=<ToCopyBackward0>)
tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 36,  0,  0,  0, 18,  0,  5,  5,
         0,  0, 49,  0,  8,  0, 46,  0,  0,  0,  0,  6,  0,  4, 10,  0,  0,  0,
         0, 25, 25, 17,  0,  0,  8,  0, 49,  0,  0,  0, 25, 25,  0, 36,  0,  0,
         0,  0,  4,  4,  0,  0, 30,  0,  0,  0,  0, 26,  0, 17,  0,  

# Push

In [ ]:
# save the checkpoint for inference
trainer.push_to_hub()

model.safetensors:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

events.out.tfevents.1701625920.a267f566d234.607.1:   0%|          | 0.00/406 [00:00<?, ?B/s]

events.out.tfevents.1701624997.a267f566d234.607.0:   0%|          | 0.00/6.59k [00:00<?, ?B/s]

Upload 4 LFS files:   0%|          | 0/4 [00:00<?, ?it/s]

training_args.bin:   0%|          | 0.00/4.60k [00:00<?, ?B/s]

'https://huggingface.co/Roxysun/wav2vec2-large-xls-r-300m-cs-colab-phoneme/tree/main/'

# Test Fine-tuned model

In [ ]:
model = Wav2Vec2ForCTC.from_pretrained("Roxysun/"+repo_name).to("cuda")
# processor = Wav2Vec2Processor.from_pretrained(repo_name)
processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-lv-60-espeak-cv-ft")

config.json:   0%|          | 0.00/2.34k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.26G [00:00<?, ?B/s]

In [ ]:
input_dict = processor(common_voice_test[0]["input_values"], return_tensors="pt", padding=True)
print(input_dict)

logits = model(input_dict.input_values.to("cuda")).logits
print(logits)

pred_ids = torch.argmax(logits, dim=-1)[0]
print(pred_ids)


print("Prediction:")
print(processor.decode(pred_ids))

print("\nReference:")
print(common_voice_test_2[0][sentence].lower())

It is strongly recommended to pass the ``sampling_rate`` argument to this function. Failing to do so can result in silent errors that might be hard to debug.


{'input_values': tensor([[-0.0042,  0.0136, -0.0304,  ...,  0.0295,  0.0304,  0.0276]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1]], dtype=torch.int32)}
tensor([[[ 13.3405, -18.9673, -18.4958,  ..., -17.5683, -19.0762, -18.3085],
         [ 13.5883, -19.3639, -18.8795,  ..., -17.9117, -19.4800, -18.6497],
         [ 13.3618, -18.9545, -18.4490,  ..., -17.4968, -19.0915, -18.3020],
         ...,
         [  8.7554, -13.3706, -13.0808,  ..., -12.4819, -13.6449, -12.9091],
         [  7.9066, -12.7005, -12.4297,  ..., -11.8501, -12.9748, -12.2819],
         [  8.5039, -13.4810, -13.1081,  ..., -12.5592, -13.7766, -13.1026]]],
       device='cuda:0', grad_fn=<ViewBackward0>)
tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 36,  0,  0,  0, 18,  0,  5,  5,
         0,  0, 49,  0,  8,  0, 46,  0,  0,  0,  0,  6,  0,  4, 10,  0,  0,  0,
         0, 25, 25, 17,  0,  0,  8,  0, 49,  0,  0,  0, 25, 25,  0, 36,  0,  0,
         0,  0,  4,  4,  0,  0, 30,  0,  0,  0,  0, 26,  0, 17,  0,  0,